name: flutter_practice_ui
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  interpolate: ^1.0.2+2
  url_launcher: ^5.7.10
  google_maps_flutter: ^1.2.0
  location: ^3.0.2
  geolocator: ^5.1.4+2
  dio: ^3.0.9
  http: ^0.12.0+4
  rxdart: ^0.23.1
  maps_toolkit: ^1.0.1+3
  flutter_hooks: ^0.15.0
  quiver: ^2.1.5
  pedantic: ^1.8.0

  #youtube clone
  miniplayer: ^1.0.0+2
  flutter_riverpod: ^0.14.0+3
  timeago: ^3.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - asset/image/
